(() => {
  const componentConnection = 'BedrockComponent';
  const jsonBlocks = [
    { type:'bedrock_entity_root', message0:'Entidad %1:%2', args0:[{type:'field_input',name:'NAMESPACE',text:'poppy'},{type:'field_input',name:'IDENTIFIER',text:'test_creature'}], message1:'huevo de aparición %1 invocable %2', args1:[{type:'field_checkbox',name:'SPAWNABLE',checked:true},{type:'field_checkbox',name:'SUMMONABLE',checked:true}], message2:'componentes %1', args2:[{type:'input_statement',name:'COMPONENTS',check:componentConnection}], colour:225, tooltip:'Raíz de una entidad de Behavior Pack.', helpUrl:'https://learn.microsoft.com/minecraft/creator/documents/introductiontoaddentity' },
    { type:'bedrock_health', message0:'❤️ Vida actual %1 máxima %2', args0:[{type:'field_number',name:'VALUE',value:20,min:1,precision:1},{type:'field_number',name:'MAX',value:20,min:1,precision:1}], previousStatement:componentConnection,nextStatement:componentConnection,colour:0,tooltip:'minecraft:health' },
    { type:'bedrock_physics', message0:'🌍 Física gravedad %1 colisión %2', args0:[{type:'field_checkbox',name:'GRAVITY',checked:true},{type:'field_checkbox',name:'COLLISION',checked:true}], previousStatement:componentConnection,nextStatement:componentConnection,colour:195,tooltip:'minecraft:physics' },
    { type:'bedrock_collision_box', message0:'📦 Caja de colisión ancho %1 alto %2', args0:[{type:'field_number',name:'WIDTH',value:0.8,min:0.01,precision:0.01},{type:'field_number',name:'HEIGHT',value:1.8,min:0.01,precision:0.01}], previousStatement:componentConnection,nextStatement:componentConnection,colour:195,tooltip:'minecraft:collision_box' },
    { type:'bedrock_movement', message0:'🏃 Velocidad de movimiento %1', args0:[{type:'field_number',name:'VALUE',value:0.25,min:0,precision:0.01}], previousStatement:componentConnection,nextStatement:componentConnection,colour:120,tooltip:'minecraft:movement' },
    { type:'bedrock_movement_basic', message0:'↪️ Movimiento básico giro máximo %1°', args0:[{type:'field_number',name:'MAX_TURN',value:30,min:0,max:180,precision:1}], previousStatement:componentConnection,nextStatement:componentConnection,colour:120,tooltip:'minecraft:movement.basic' },
    { type:'bedrock_navigation_generic', message0:'🧭 Navegación caminar %1 nadar %2 abrir puertas %3', args0:[{type:'field_checkbox',name:'WALK',checked:true},{type:'field_checkbox',name:'SWIM',checked:false},{type:'field_checkbox',name:'DOORS',checked:true}], previousStatement:componentConnection,nextStatement:componentConnection,colour:120,tooltip:'minecraft:navigation.generic' },
    { type:'bedrock_jump_static', message0:'⬆️ Salto potencia %1', args0:[{type:'field_number',name:'POWER',value:0.42,min:0,precision:0.01}], previousStatement:componentConnection,nextStatement:componentConnection,colour:120,tooltip:'minecraft:jump.static' },
    { type:'bedrock_type_family', message0:'🏷️ Familias %1', args0:[{type:'field_input',name:'FAMILIES',text:'mob,custom'}], previousStatement:componentConnection,nextStatement:componentConnection,colour:285,tooltip:'minecraft:type_family. Separa familias con comas.' },
    { type:'bedrock_random_stroll', message0:'🚶 Pasear prioridad %1 velocidad × %2', args0:[{type:'field_number',name:'PRIORITY',value:8,min:0,precision:1},{type:'field_number',name:'SPEED',value:1,min:0,precision:0.1}], previousStatement:componentConnection,nextStatement:componentConnection,colour:35,tooltip:'minecraft:behavior.random_stroll' },
    { type:'bedrock_look_at_player', message0:'👀 Mirar jugador prioridad %1 distancia %2 probabilidad %3', args0:[{type:'field_number',name:'PRIORITY',value:7,min:0,precision:1},{type:'field_number',name:'DISTANCE',value:6,min:0,precision:0.5},{type:'field_number',name:'PROBABILITY',value:0.02,min:0,max:1,precision:0.01}], previousStatement:componentConnection,nextStatement:componentConnection,colour:35,tooltip:'minecraft:behavior.look_at_player' },
    { type:'bedrock_nearest_player', message0:'🎯 Detectar jugador prioridad %1 distancia %2 debe verlo %3', args0:[{type:'field_number',name:'PRIORITY',value:2,min:0,precision:1},{type:'field_number',name:'DISTANCE',value:32,min:1,precision:1},{type:'field_checkbox',name:'MUST_SEE',checked:true}], previousStatement:componentConnection,nextStatement:componentConnection,colour:15,tooltip:'minecraft:behavior.nearest_attackable_target para jugadores.' },
    { type:'bedrock_melee_attack', message0:'⚔️ Ataque cuerpo a cuerpo prioridad %1 velocidad × %2 seguir objetivo %3', args0:[{type:'field_number',name:'PRIORITY',value:3,min:0,precision:1},{type:'field_number',name:'SPEED',value:1.2,min:0,precision:0.1},{type:'field_checkbox',name:'TRACK',checked:true}], previousStatement:componentConnection,nextStatement:componentConnection,colour:15,tooltip:'minecraft:behavior.melee_attack' },
    { type:'bedrock_attack_damage', message0:'💥 Daño de ataque %1', args0:[{type:'field_number',name:'DAMAGE',value:6,min:0,precision:1}], previousStatement:componentConnection,nextStatement:componentConnection,colour:15,tooltip:'minecraft:attack' },
    { type:'bedrock_custom_component', message0:'🧪 Componente avanzado %1 valor JSON %2', args0:[{type:'field_input',name:'KEY',text:'minecraft:nameable'},{type:'field_input',name:'JSON',text:'{}'}], previousStatement:componentConnection,nextStatement:componentConnection,colour:315,tooltip:'Añade manualmente un componente todavía no cubierto por bloques.' }
  ];
  Blockly.defineBlocksWithJsonArray(jsonBlocks);
  window.BedrockBlocks = { toolbox:{ kind:'categoryToolbox', contents:[
    {kind:'category',name:'🧱 Entidad',colour:'#6477ff',contents:[{kind:'block',type:'bedrock_entity_root'}]},
    {kind:'category',name:'❤️ Base',colour:'#e24f5f',contents:[{kind:'block',type:'bedrock_health'},{kind:'block',type:'bedrock_physics'},{kind:'block',type:'bedrock_collision_box'},{kind:'block',type:'bedrock_type_family'}]},
    {kind:'category',name:'🏃 Movimiento',colour:'#43a047',contents:[{kind:'block',type:'bedrock_movement'},{kind:'block',type:'bedrock_movement_basic'},{kind:'block',type:'bedrock_navigation_generic'},{kind:'block',type:'bedrock_jump_static'}]},
    {kind:'category',name:'🧠 IA',colour:'#f59d3d',contents:[{kind:'block',type:'bedrock_random_stroll'},{kind:'block',type:'bedrock_look_at_player'},{kind:'block',type:'bedrock_nearest_player'},{kind:'block',type:'bedrock_melee_attack'},{kind:'block',type:'bedrock_attack_damage'}]},
    {kind:'category',name:'🧪 Avanzado',colour:'#ab47bc',contents:[{kind:'block',type:'bedrock_custom_component'}]}
  ]}};
})();
